### ISSUE TITLE
6.4.0版本 /_ansj/flush/dic 不能刷新所有词典

### ISSUE THREAD

**Issue by xuganggogo** [NLPchina/elasticsearch-analysis-ansj#136]
6.4.0版本 /_ansj/flush/dic 不能刷新所有词典。报错如下
`[2018-10-09T14:36:11,348][INFO ][o.a.e.a.TransportAnsjAction] to flush {key=null}
java.lang.NullPointerException
        at org.ansj.elasticsearch.action.TransportAnsjAction.flushDic(TransportAnsjAction.java:367)
        at org.ansj.elasticsearch.action.TransportAnsjAction.shardOperation(TransportAnsjAction.java:87)
        at org.ansj.elasticsearch.action.TransportAnsjAction.shardOperation(TransportAnsjAction.java:48)
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:287)
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:280)
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:30)
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:251)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:309)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66)
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:665)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`

试了一下必须的加参数指定词典名称，如
/_ansj/flush/dic?key=dic_1

**Comment by shi-yuan** [comment]
是的，得传参数
