### ISSUE TITLE
使用jdbc的方式自定义词库，启动报错SqlCallback

### ISSUE THREAD

**Issue by jiyourui** [NLPchina/elasticsearch-analysis-ansj#143]

**Comment by jiyourui** [comment]
我配置了jdbc mysql的访问方式去自定义词典，但是启动的时候报错，啥原因呢
报错内容：
org.elasticsearch.bootstrap.StartupException: org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: org/nutz/dao/sql/SqlCallback
  at org.ansj.elasticsearch.index.config.AnsjElasticConfigurator.<init>(Unknown Source)
  while locating org.ansj.elasticsearch.index.config.AnsjElasticConfigurator
Caused by: java.lang.NoClassDefFoundError: org/nutz/dao/sql/SqlCallback
        at org.ansj.util.MyStaticValue.<clinit>(MyStaticValue.java:99)
        at org.ansj.elasticsearch.index.config.AnsjElasticConfigurator.flushConfig(AnsjElasticConfigurator.java:76)
        at org.ansj.elasticsearch.index.config.AnsjElasticConfigurator.<init>(AnsjElasticConfigurator.java:68)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

**Comment by jiyourui** [comment]
这个问题，我已经解决了，除了修改plugin-security.policy，增加JDBC的驱动包以外，我修改了ansj_seg的jar包，将jdbc2stream里面的静态初始化驱动包只设置了我需要的com.mysql.jdbc.Driver，这个地方是ansj的设置，可能我的版本比较低，我用的是5.1.2的版本

**Comment by jiyourui** [comment]
嗯嗯，我测试了一下ansj_seg.5.1.3的版本，没有问题了。还有一个问题，我看到userLibrary取消了，只能用dic来设置自定义词典了，那么之前是有一个默认的文件词典--default.doc，怎么和自定义的词典库一块使用呢？

**Comment by PKFresher** [comment]
在 ansj.cfg.yml 中  填写dic: //自己的词典
使用查询的时候 使用dic_ansj为自己的词典,使用query_ansj两个一起.

**Comment by jiyourui** [comment]
@PKFresher 似乎不是这样的，我用过dic设置的自定义词典，通过index_ansj、query_ansj使用，没有用dic_ansj依然生效

**Comment by jiyourui** [comment]
@shi-yuan @PKFresher 我要实现的需求是这样的：对“ssh登录”这个短语做分词，如果使用默认的default.dic这个默认加载的词库，分出开的是“ssh”、“登录”、“登”、“录”，如果我要使用自定义的，分出来的只有“ssh登录”，而我正真想要的是这两个词库都生效。我在ansj_library.properties里面两个都配置了：
# 默认词典
dic=file://../plugins/elasticsearch-analysis-ansj/default.dic
# 自定义
userLibrary=jdbc://jdbc:mysql:XXX
但是无法满足我的需求

**Comment by jiyourui** [comment]
OK，我的功能实现了，还有一个比较冷的问题，重新加载词典库对elasticsearch数据入库的影响大吗？比如时间、内存的消耗之类的

**Comment by jiyourui** [comment]
了解了，到时候在实践中看看吧，毕竟刷新词库的频率还是比较低的。

**Comment by shi-yuan** [comment]
恩恩，刷新所有的频率是比较低的，不过刷新某个词典，还是有的
