### ISSUE TITLE
elasticsearch 2.3.1  版本索引时出错

### ISSUE THREAD

**Issue by jonnyzheng** [NLPchina/elasticsearch-analysis-ansj#20]
创建index没有问题，开始索引数据时出现错误：
```
[2016-04-23 17:45:27,284][WARN ][rest.suppressed          ] /products/product/13 Params: {index=products, id=13, type=product}
RemoteTransportException[[Lightbright][127.0.0.1:9300][indices:data/write/index[p]]]; nested: NullPointerException;
Caused by: java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at org.ansj.util.AnsjReader.<init>(AnsjReader.java:34)
	at org.ansj.util.AnsjReader.<init>(AnsjReader.java:49)
	at org.ansj.splitWord.analysis.IndexAnalysis.<init>(IndexAnalysis.java:133)
	at org.ansj.lucene5.AnsjAnalyzer.getTokenizer(AnsjAnalyzer.java:95)
	at org.ansj.elasticsearch.index.analysis.AnsjAnalysis$1.create(AnsjAnalysis.java:59)
	at org.elasticsearch.index.analysis.CustomAnalyzer.createComponents(CustomAnalyzer.java:83)
	at org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:101)
	at org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:101)
	at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:176)
	at org.apache.lucene.document.Field.tokenStream(Field.java:562)
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:628)
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:365)
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:321)
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:234)
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:450)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1477)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1256)
	at org.elasticsearch.index.engine.InternalEngine.innerIndex(InternalEngine.java:530)
	at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:457)
	at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:601)
	at org.elasticsearch.index.engine.Engine$Index.execute(Engine.java:836)
	at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:237)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:158)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:66)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:639)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:271)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

我的配置文件如下:

```
index:
  analysis:
    analyzer:
      customer_ansj_index:
        tokenizer: index_ansj
      customer_ansj_query:
        tokenizer: query_ansj
```

**Comment by ansjsun** [comment]
应该是配置的问题



如果你想把ansj作为你的默认分词需要在elasticsearch.yml加入如下配置:

····

#默认分词器,索引
index.analysis.analyzer.default.type: index_ansj

#默认分词器,查询

index.analysis.analyzer.default_search.type: query_ansj

····

如果通过mapping来设置。。那么什么都不要配置。。就可以

**Comment by ansjsun** [comment]
你好这个错误还存在嘛？

**Comment by jonnyzheng** [comment]
@ansjsun 我测试过了，只写默认分词器的时候才可以，如果加了自定义analyzer的话那么就会出错误，我简单配置的也不行:


```
index:
  analysis:
    analyzer:
      customer_ansj_index:
        tokenizer: index_ansj
      customer_ansj_query:
        tokenizer: query_ansj

```

本来我想加一些同义词和停用词的

**Comment by ansjsun** [comment]
哦。。

````
index:
  analysis:
    analyzer:
      customer_ansj_index:
        tokenizer: index_ansj
      customer_ansj_query:
        tokenizer: query_ansj
````

这种配置除了加 同义词和停用词。其他情况下应该应该也用不到吧。。具体为什么我也不知道。。。

**Comment by jonnyzheng** [comment]
恩恩，好吧，我再多试试吧，不行就不升级了

**Comment by ansjsun** [comment]
我觉得时es语法改了吧。。分词插件是按照官方例子来实现的。其它分词器应该也不可以这么配置了

**Comment by jonnyzheng** [comment]
@ansjsun 好的，我再去看看2.3.1的文档

**Comment by ansjsun** [comment]
@jonnyzheng 不好意思应该是我的错.你把插件删除重新安装下.这次好了
