### ISSUE TITLE
使用自定义停用词库后报错

### ISSUE THREAD

**Issue by tushunlin** [NLPchina/elasticsearch-analysis-ansj#204]
![image](https://user-images.githubusercontent.com/15681692/146140844-1f80df45-e657-48f6-9e38-c193e30b45b0.png)

这是我测试的文字 “钟南山说今年年底大家还是可以出门的，记得带好口罩去吃大闸蟹了”
然后我把标点符号放到自定义停用词库了，报了个数组越界。

报错如下：
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.String.charAt(String.java:658) ~[?:1.8.0_181]
        at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.validateIndexOrAliasName(MetadataCreateIndexService.java:237) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.validateIndexName(MetadataCreateIndexService.java:181) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.validate(MetadataCreateIndexService.java:1005) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:332) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:377) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.action.admin.indices.create.AutoCreateAction$TransportAction$1.execute(AutoCreateAction.java:137) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:702) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:324) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:219) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:73) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) ~[elasticsearch-7.10.0.jar:7.10.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[2021-12-15T15:16:32,620][WARN ][r.suppressed             ] [node-1] path: //_ansj, params: {index=, op_type=create, type=_ansj}
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.String.charAt(String.java:658) ~[?:1.8.0_181]
        at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.validateIndexOrAliasName(MetadataCreateIndexService.java:237) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.validateIndexName(MetadataCreateIndexService.java:181) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.validate(MetadataCreateIndexService.java:1005) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:332) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:377) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.action.admin.indices.create.AutoCreateAction$TransportAction$1.execute(AutoCreateAction.java:137) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:702) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:324) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:219) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:73) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678) [elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) ~[elasticsearch-7.10.0.jar:7.10.0]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) ~[elasticsearch-7.10.0.jar:7.10.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by tushunlin** [comment]
对了 ，发现器连用也出现了类似的问题：
比如：
Result modifResult = DicAnalysis.parse(str,DicLibrary.gets(Dictionary.userDic,DicLibrary.DEFAULT)).recognition(Dictionary.getStopFilter()).recognition(new EmailRecognition());
System.out.println(modifResult);

同样也是经过停用词过滤之后。
报错如下：
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 37
	at org.ansj.util.Graph.getMaxTerm(Graph.java:174)
	at org.ansj.util.Graph.rmLittlePath(Graph.java:144)
	at org.ansj.app.extracting.Extracting.parse(Extracting.java:130)
	at org.ansj.app.extracting.Extracting.parse(Extracting.java:113)
	at org.ansj.recognition.impl.EmailRecognition.recognition(EmailRecognition.java:38)
	at org.ansj.domain.Result.recognition(Result.java:53)
	at varyag.WordEngine.ansj_analysis(WordEngine.java:54)
	at varyag.WordEngine.main(WordEngine.java:48)

**Comment by shi-yuan** [comment]
str、词典内容，麻烦提供下
