### ISSUE TITLE
请问后续能支持8.4.1版本吗?8.3.3版本安装不上

### ISSUE THREAD

**Issue by rory5515** [NLPchina/elasticsearch-analysis-ansj#218]
请问后续能支持8.4.1版本吗?8.3.3版本安装不上.
或者有没有什么办法可以配置到8.4.1版本的?

**Comment by shi-yuan** [comment]
8.3.3版本安装不上？具体什么问题

8.4.1版本的话，应该只需要升级es版本，重新打包即可

**Comment by rory5515** [comment]
我升级了ES版本,想在8.4.3上跑起来,结果没有成功
```
fatal exception while booting Elasticsearch
org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) Could not find a suitable constructor in org.ansj.elasticsearch.index.config.AnsjElasticConfigurator. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at org.ansj.elasticsearch.index.config.AnsjElasticConfigurator.class(Unknown Source)
  while locating org.ansj.elasticsearch.index.config.AnsjElasticConfigurator
    for parameter 5 at org.ansj.elasticsearch.action.TransportAnsjAction.<init>(Unknown Source)
  at _unknown_

1 error
	at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:371) ~[elasticsearch-8.4.3.jar:?]
	at org.elasticsearch.common.inject.InjectorBuilder.initializeStatically(InjectorBuilder.java:116) ~[elasticsearch-8.4.3.jar:?]
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:74) ~[elasticsearch-8.4.3.jar:?]
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:69) ~[elasticsearch-8.4.3.jar:?]
	at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:31) ~[elasticsearch-8.4.3.jar:?]
	at org.elasticsearch.node.Node.<init>(Node.java:1052) ~[elasticsearch-8.4.3.jar:?]
	at org.elasticsearch.node.Node.<init>(Node.java:311) ~[elasticsearch-8.4.3.jar:?]
	at org.elasticsearch.bootstrap.Elasticsearch$2.<init>(Elasticsearch.java:214) ~[elasticsearch-8.4.3.jar:?]
	at org.elasticsearch.bootstrap.Elasticsearch.initPhase3(Elasticsearch.java:214) ~[elasticsearch-8.4.3.jar:?]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67) ~[elasticsearch-8.4.3.jar:?]
```

**Comment by shi-yuan** [comment]
插件升级吧，这个地方改过了

**Comment by rory5515** [comment]
> 插件升级吧，这个地方改过了

好的,非常感谢
