### ISSUE TITLE
8.7.1版本 _analyze 报错

### ISSUE THREAD

**Issue by Doobetter** [NLPchina/elasticsearch-analysis-ansj#228]
GET _analyze
{
   "analyzer": "query_ansj",
  "text": "中国"
}

Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
        at java.io.StringReader.<init>(StringReader.java:51) ~[?:?]
        at org.ansj.lucene7.AnsjAnalyzer.createComponents(AnsjAnalyzer.java:68) ~[?:?]

**Comment by shi-yuan** [comment]
ansj lucene plug需要升级，会尽快处理

**Comment by shi-yuan** [comment]
```xml
<dependency>
	<groupId>org.ansj</groupId>
	<artifactId>ansj_lucene9_plug</artifactId>
	<version>5.1.5.2</version>
</dependency>
```
