### ISSUE TITLE
无法在自定义analyzer中添加index_ansj

### ISSUE THREAD

**Issue by suclogger** [NLPchina/elasticsearch-analysis-ansj#24]
elasticsearch版本：2.3.3

`elasticsearch.yml `配置如下：

```
index :
  analysis :
    tokenizer :
      index_ansj :
        type : index_ansj
    filter :
      ini_synonym :
        type : synonym
        synonyms_path: ansj/dic/synonym.txt
    analyzer :
      custom1 :
        tokenizer : index_ansj
        filter : [ini_synonym]


index.analysis.analyzer.default.type: custom1
```
启动的时候会打印日志：
```
[.kibana] IndexCreationException[failed to create index]; nested: IllegalArgumentException[Unknown Analyzer type [custom1] for [default]];
        at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:362)
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewIndices(IndicesClusterStateService.java:294)
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:163)
        at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:610)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Unknown Analyzer type [custom1] for [default]
        at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:320)
        at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:60)
        at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:233)
        at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:105)
        at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:143)
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
        at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:157)
        at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:55)
        at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:358)
```

**Comment by shi-yuan** [comment]
如果需要定义默认的，直接配置：
`index.analysis.analyzer.default.type: index_ansj`
如果需要用一个自定义的：
```
index.analysis.analyzer.default.type: custom
index.analysis.analyzer.default.tokenizer: index_ansj
index.analysis.analyzer.default.filter: [ini_synonym]
```

**Comment by suclogger** [comment]
这样配置之后就ok了，感谢，可以close了
