### ISSUE TITLE
通过redis发布词条的功能失效

### ISSUE THREAD

**Issue by suclogger** [NLPchina/elasticsearch-analysis-ansj#26]
elasticsearch版本：2.3.3
插件版本：2.3.3.2

添加`-Des.security.manager.enabled=false`启动有报错提示：
```
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:22)
	at org.ansj.elasticsearch.pubsub.redis.RedisUtils.getConnection(RedisUtils.java:22)
	at org.ansj.elasticsearch.index.config.AnsjElasticConfigurator$1.run(AnsjElasticConfigurator.java:85)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.NoSuchElementException: Could not create a validated object, cause: ValidateObject failed
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1203)
	at redis.clients.util.Pool.getResource(Pool.java:20)
	... 3 more
[2016-07-02 21:23:23,838][ERROR][ansj-redis-utils         ] Could not get a resource from the pool
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:22)
	at org.ansj.elasticsearch.pubsub.redis.RedisUtils.getConnection(RedisUtils.java:22)
	at org.ansj.elasticsearch.index.config.AnsjElasticConfigurator$1.run(AnsjElasticConfigurator.java:85)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.NoSuchElementException: Could not create a validated object, cause: ValidateObject failed
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1203)
	at redis.clients.util.Pool.getResource(Pool.java:20)
	... 3 more
[2016-07-02 21:23:23,839][INFO ][ansj-initializer         ] redis守护线程准备完毕,ip:127.0.0.1:6379,port:6379,channel:ansj_term
Exception in thread "Thread-3" java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at org.ansj.elasticsearch.index.config.AnsjElasticConfigurator$1.run(AnsjElasticConfigurator.java:89)
	at java.lang.Thread.run(Thread.java:745)
```

通过channal发布，没有产生ext.dic 文件而且添加的词条也没起作用。

**Comment by shi-yuan** [comment]
重新install一下最新的，不用添加-Des.security.manager.enabled=false，试试

**Comment by suclogger** [comment]
我装的是最新的2.3.3.2，添加和不添加都有这个报错

**Comment by suclogger** [comment]
![image](https://cloud.githubusercontent.com/assets/8472155/16540622/d4a226c4-409d-11e6-9387-e6d8bd74ca60.png)

**Comment by shi-yuan** [comment]
你可以看看redis的连接数，是不是很多连接数。
试着根据需要配置redis.pool.maxactive，redis.pool.maxidle，redis.pool.maxwait，redis.pool.testonborrow

**Comment by suclogger** [comment]
我将`testonborrow`设置为false之后出现报错：
```
Exception in thread "Thread-3" redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required.
	at redis.clients.jedis.Protocol.processError(Protocol.java:54)
	at redis.clients.jedis.Protocol.process(Protocol.java:61)
	at redis.clients.jedis.Protocol.read(Protocol.java:122)
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:196)
	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:88)
	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:83)
	at redis.clients.jedis.Jedis.subscribe(Jedis.java:1974)
	at org.ansj.elasticsearch.index.config.AnsjElasticConfigurator$1.run(AnsjElasticConfigurator.java:90)
	at java.lang.Thread.run(Thread.java:745)
```

是否因为redis需要认证的关系？

**Comment by shi-yuan** [comment]
设置了密码认证？

**Comment by suclogger** [comment]
是的

**Comment by shi-yuan** [comment]
目前版本，还没提供这个参数的配置

**Comment by suclogger** [comment]
![image](https://cloud.githubusercontent.com/assets/8472155/16540713/bfd89f72-40a0-11e6-9803-45bef25d7111.png)
这里添加jedis.auth是否可行？

**Comment by shi-yuan** [comment]
内部已提供构造函数new JedisPool(config, ip, port, 2000, "password")，可以直接把配置信息传过去

**Comment by suclogger** [comment]
添加了认证之后启动ok，功能也正常。
建议更新一下readme的相关内容：
>redis使用的jar用默认脚本启动会有权限问题，此问题目前只能加./elasticsearch -Des.security.manager.enabled=false参数来解决 如果谁有更好的方法请q我
因为要使用redis的pubsub功能，需要关闭es的权限控制，请慎重使用。

而且
>write:
    dic: "ext.dic" ##如果有使用redis的pubsub方式更新词典，默认使用 这个目录是相对于dic_path

这里的相对于dic_path，其实是相对于elasticsearch的config目录。
感谢。
如果能更新添加密码配置的部分就更好啦~

**Comment by suclogger** [comment]
目前ext.dic的位置放在elasticsearch的config目录会导致重启之后这里面的内容没有加载。

**Comment by shi-yuan** [comment]
近期会尽快更新，thx！

**Comment by shi-yuan** [comment]
redis发布新词的功能，最好别用。
同步更新时，如果失败或者在更新的过程中有数据写入索引，这时数据索引其实是不对的；
如果非要使用，必须得确保同步更新成功，而且必须得等同步更新完成后，才能索引数据

**Comment by suclogger** [comment]
>同步更新时，如果失败或者在更新的过程中有数据写入索引，这时数据索引其实是不对的；

这里的不对，指的是数据没有按照添加的词条来建立索引？
我感觉这个应该不是很大问题，因为索引中的历史数据是需要根据最新添加的词条重新索引一遍的，既然重新索引这个操作是必须的，同步更新时写入的数据自然不成问题。

而且目前出了redis发布的方式，其他方式只能是修改词典文件，推送到es，重启es，重建索引一系列操作才能添加词条。这样实在是比较麻烦。

如果这里更好一点的话，可否控制通过rediss发布的词条只影响query_ansj，不影响index_ansj，这样可以确保索引中的数据比较统一。

**Comment by shi-yuan** [comment]
redis发布新词，很可能会出现，一些节点没有同步更新

目前，词典是公共的，词条的变更会影响所有ansj analyzer的分词效果

**Comment by suclogger** [comment]
目前2个node的情况下同步还是比较理想，再观察一段时间，如果有问题再开issue，这个先close吧。
感谢。

**Comment by shi-yuan** [comment]
客气，有问题及时提哈，大家相互学习！
