### ISSUE TITLE
ambiguity词典自定义路径失效，redis发布报错

### ISSUE THREAD

**Issue by rocky-zh** [NLPchina/elasticsearch-analysis-ansj#32]
配置文件如下：

```yml
ambiguity_path: "/绝对路径/config/ansj/dic/ambiguity.dic"
```
通过redis-cli发布

```
publish ansj_term a:c:减肥瘦身-减肥,nr,瘦身,v
```

错误日志如下：

```
[2016-09-19 09:13:06,710][ERROR][ansj-redis-msg-file      ] appendAMB exception
java.security.PrivilegedActionException: java.io.FileNotFoundException: ansj/dic/ambiguity.dic (没有那个文件或目录)
       	at java.security.AccessController.doPrivileged(Native Method)
       	at org.ansj.elasticsearch.pubsub.redis.FileUtils.appendFile(FileUtils.java:71)
       	at org.ansj.elasticsearch.pubsub.redis.FileUtils.appendAMB(FileUtils.java:58)
       	at org.ansj.elasticsearch.pubsub.redis.AddTermRedisPubSub.onMessage(AddTermRedisPubSub.java:38)
       	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:113)
       	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:83)
       	at redis.clients.jedis.Jedis.subscribe(Jedis.java:1974)
       	at org.ansj.elasticsearch.index.config.AnsjElasticConfigurator$1.run(AnsjElasticConfigurator.java:93)
       	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: ansj/dic/ambiguity.dic (没有那个文件或目录)
       	at java.io.FileOutputStream.open(Native Method)
       	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
       	at java.io.FileWriter.<init>(FileWriter.java:107)
       	at org.ansj.elasticsearch.pubsub.redis.FileUtils$1.run(FileUtils.java:74)
       	... 9 more
java.security.PrivilegedActionException: java.io.FileNotFoundException: ansj/dic/ambiguity.dic (没有那个文件或目录)
       	at java.security.AccessController.doPrivileged(Native Method)
       	at org.ansj.elasticsearch.pubsub.redis.FileUtils.appendFile(FileUtils.java:71)
       	at org.ansj.elasticsearch.pubsub.redis.FileUtils.appendAMB(FileUtils.java:58)
       	at org.ansj.elasticsearch.pubsub.redis.AddTermRedisPubSub.onMessage(AddTermRedisPubSub.java:38)
       	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:113)
       	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:83)
       	at redis.clients.jedis.Jedis.subscribe(Jedis.java:1974)
       	at org.ansj.elasticsearch.index.config.AnsjElasticConfigurator$1.run(AnsjElasticConfigurator.java:93)
       	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: ansj/dic/ambiguity.dic (没有那个文件或目录)
       	at java.io.FileOutputStream.open(Native Method)
       	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
       	at java.io.FileWriter.<init>(FileWriter.java:107)
       	at org.ansj.elasticsearch.pubsub.redis.FileUtils$1.run(FileUtils.java:74)
       	... 9 more
```

之后跟踪FileUtils.java发现
![1](https://cloud.githubusercontent.com/assets/1244039/18621081/d9ed949c-7e50-11e6-9d7f-26914ed5005e.png)
怀疑版本代码升级中将相对路径丢失后引起错误

**Comment by shi-yuan** [comment]
谢谢！
请问，你用的版本是？

**Comment by rocky-zh** [comment]
7.3日，pom.xml未升级2.3.4的版本

**Comment by shi-yuan** [comment]
master上修复，你自己根据需要打一个包吧？

**Comment by rocky-zh** [comment]
OK,等待patch，我自行合并
