### ISSUE TITLE
plugin-descriptorn改成5.3.0报错了

### ISSUE THREAD

**Issue by longshang** [NLPchina/elasticsearch-analysis-ansj#65]
2) Could not find a suitable constructor in org.elasticsearch.rest.RestController. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at org.elasticsearch.rest.RestController.class(Unknown Source)
  while locating org.elasticsearch.rest.RestController
    **for parameter 1 at org.ansj.elasticsearch.cat.AnsjCatAction.<init>(Unknown Source)**
  at _unknown_

2 errors
        at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:361) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.inject.InjectorBuilder.initializeStatically(InjectorBuilder.java:137) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:93) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:96) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:43) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.node.Node.<init>(Node.java:482) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.node.Node.<init>(Node.java:238) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.0.jar:5.3.0]
        ... 6 more

**Comment by shi-yuan** [comment]
如果用5.3.0，修改AnalysisAnsjPlugin：
```java
...
    @Override
    public List<RestHandler> getRestHandlers(Settings settings, RestController restController, ClusterSettings clusterSettings, IndexScopedSettings indexScopedSettings, SettingsFilter settingsFilter, IndexNameExpressionResolver indexNameExpressionResolver, Supplier<DiscoveryNodes> nodesInCluster) {
        return Arrays.asList(
                new RestAnsjAction(settings, restController),
                new AnalyzerCatAction(settings, restController),
                new AnsjCatAction(settings, restController));
    }

    private class AnsjModule extends AbstractModule {
        @Override
        protected void configure() {
            bind(AnsjElasticConfigurator.class).asEagerSingleton();
        }
    }
```

**Comment by shi-yuan** [comment]
现在master已经支持5.3.0了，可以看看哈

**Comment by longshang** [comment]
@shi-yuan ,5.3.0分支，mvn clean install,报错了：
[ERROR] Failed to execute goal on project elasticsearch-analysis-ansj: Could not resolve dependencies for project org.ansj:elasticsearch-analysis-ansj:jar:5.3.0.0: The following artifacts could not be resolved: org.ansj:ansj_seg:jar:5.1.1, org.elasticsearch:elasticsearch:jar:5.3.0: Could not transfer artifact org.ansj:ansj_seg:jar:5.1.1 from/to central (https://repo.maven.apache.org/maven2): GET request of: org/ansj/ansj_seg/5.1.1/ansj_seg-5.1.1.jar from central failed: Premature end of Content-Length delimited message body (expected: 20677521; received: 8407024 -> [Help 1]
