### ISSUE TITLE
好像词库无效

### ISSUE THREAD

**Issue by janson1983** [NLPchina/elasticsearch-analysis-ansj#70]
我用的是5.3.0的版本。在启动elastic时查看日志，分别进行了二种方式，一种是正确加载了各种词库的模式。另一种是把词库移动后，再重新启动 elastic，日志中一堆的关于加载词库的错误。而这二种情况下，分词出来的结果具然是一模一样的。有谁知道是什么原因吗？就是说分词并没有使用词库。日志报错如下：

[2017-04-25T22:00:15,019][INFO ][o.a.e.p.AnalysisAnsjPlugin] regedit analyzer tokenizer named : base_ansj
[2017-04-25T22:00:15,019][INFO ][o.a.e.p.AnalysisAnsjPlugin] regedit analyzer tokenizer named : index_ansj
[2017-04-25T22:00:15,019][INFO ][o.a.e.p.AnalysisAnsjPlugin] regedit analyzer tokenizer named : query_ansj
[2017-04-25T22:00:15,019][INFO ][o.a.e.p.AnalysisAnsjPlugin] regedit analyzer tokenizer named : dic_ansj
[2017-04-25T22:00:15,019][INFO ][o.a.e.p.AnalysisAnsjPlugin] regedit analyzer tokenizer named : nlp_ansj
[2017-04-25T22:00:15,062][INFO ][o.a.e.p.AnalysisAnsjPlugin] regedit analyzer provider named : base_ansj
[2017-04-25T22:00:15,062][INFO ][o.a.e.p.AnalysisAnsjPlugin] regedit analyzer provider named : index_ansj
[2017-04-25T22:00:15,063][INFO ][o.a.e.p.AnalysisAnsjPlugin] regedit analyzer provider named : query_ansj
[2017-04-25T22:00:15,063][INFO ][o.a.e.p.AnalysisAnsjPlugin] regedit analyzer provider named : dic_ansj
[2017-04-25T22:00:15,063][INFO ][o.a.e.p.AnalysisAnsjPlugin] regedit analyzer provider named : nlp_ansj
[2017-04-25T22:00:17,842][DEBUG][o.e.a.ActionModule       ] Using REST wrapper from plugin org.elasticsearch.xpack.XPackPlugin
[2017-04-25T22:00:20,041][INFO ][ansj-initializer         ] try to load ansj config file: /newdata/elasticsearch-5.3.0/config/analysis-ansj/ansj.cfg.yml
[2017-04-25T22:00:20,047][INFO ][ansj-initializer         ] load ansj config: /newdata/elasticsearch-5.3.0/config/analysis-ansj/ansj.cfg.yml
[2017-04-25T22:00:20,148][WARN ][o.a.u.MyStaticValue      ] not find ansj_library.properties. and err {} i think it is a bug!
[2017-04-25T22:00:20,149][WARN ][o.a.u.MyStaticValue      ] not find library.properties. and err {} i think it is a bug!
java.security.AccessControlException: access denied ("java.io.FilePermission" "/home/chenjian" "read")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_121]
        at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_121]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_121]
        at java.lang.SecurityManager.checkRead(SecurityManager.java:888) ~[?:1.8.0_121]
        at java.io.File.exists(File.java:814) ~[?:1.8.0_121]
        at org.nlpcn.commons.lang.util.FileFinder.find(FileFinder.java:52) ~[nlp-lang-1.7.2.jar:?]
        at org.ansj.util.MyStaticValue.<clinit>(MyStaticValue.java:79) [ansj_seg-5.1.1.jar:?]
        at org.ansj.elasticsearch.index.config.AnsjElasticConfigurator.flushConfig(AnsjElasticConfigurator.java:78) [elasticsearch-analysis-ansj-5.3.0.0.jar:?]
        at org.ansj.elasticsearch.index.config.AnsjElasticConfigurator.<init>(AnsjElasticConfigurator.java:70) [elasticsearch-analysis-ansj-5.3.0.0.jar:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_121]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_121]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_121]
        at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:49) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:116) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:825) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:50) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:191) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:183) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:818) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:183) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:173) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:161) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:96) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:96) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:43) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.node.Node.<init>(Node.java:482) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.node.Node.<init>(Node.java:238) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.cli.Command.main(Command.java:88) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) [elasticsearch-5.3.0.jar:5.3.0]
[2017-04-25T22:00:20,208][WARN ][o.a.u.MyStaticValue      ] not find library.properties in classpath use it by default !
[2017-04-25T22:00:20,225][INFO ][o.a.d.i.File2Stream      ] path to stream ansj_library.properties
[2017-04-25T22:00:20,226][ERROR][ansj-initializer         ] ansj_library.properties load err: org.ansj.exception.LibraryException: org.ansj.exception.LibraryException:  path :ansj_library.properties file:/home/chenjian/ansj_library.properties not found or can not to read
[2017-04-25T22:00:20,231][INFO ][o.a.d.i.File2Stream      ] path to stream library/ambiguity.dic
[2017-04-25T22:00:20,232][ERROR][o.a.l.AmbiguityLibrary   ] Init ambiguity library error :java.security.AccessControlException: access denied ("java.io.FilePermission" "library/ambiguity.dic" "read"), path: library/ambiguity.dic
[2017-04-25T22:00:20,233][INFO ][o.a.d.i.File2Stream      ] path to stream default.dic
[2017-04-25T22:00:20,233][ERROR][o.a.l.DicLibrary         ] Init ambiguity library error :java.security.AccessControlException: access denied ("java.io.FilePermission" "default.dic" "read"), path: default.dic
[2017-04-25T22:00:22,390][INFO ][o.a.l.DATDictionary      ] init core library ok use time : 2119
[2017-04-25T22:00:25,099][INFO ][o.a.l.NgramLibrary       ] init ngram ok use time :2619
[2017-04-25T22:00:25,122][INFO ][ansj-initializer         ] init ansj plugin ok , goodluck youyou

**Comment by shi-yuan** [comment]
ansj.cfg.xml，是怎么配置词库的？

**Comment by Smaillife** [comment]
我也是这个问题，在群里问了没人回答

**Comment by Smaillife** [comment]
mac（maybe linux also）下自定义词典需要配字典的绝对路径
关于权限的错误：
把插件提供的plugin-security.policy中的grant添加到java.policy，
java.policy路径：/Library/Java/JavaVirtualMachines/jdk<your-jdk-version>.jdk/Contents/Home/jre/lib/security/java.policy
