### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by ahkimkoo** [NLPchina/elasticsearch-analysis-ansj#74]
```
[2017-05-12T15:12:01,623][INFO ][o.e.n.Node               ] [] initializing ...
[2017-05-12T15:12:01,749][INFO ][o.e.e.NodeEnvironment    ] [aby1GZi] using [1] data paths, mounts [[/home (/dev/sda6)]], net usable_space [203.9gb], net total_space [431.7gb], spins? [possibly], types [ext4]
[2017-05-12T15:12:01,749][INFO ][o.e.e.NodeEnvironment    ] [aby1GZi] heap size [1.9gb], compressed ordinary object pointers [true]
[2017-05-12T15:12:01,758][INFO ][o.e.n.Node               ] node name [aby1GZi] derived from node ID [aby1GZijTPe5olGx8GJoQg]; set [node.name] to override
[2017-05-12T15:12:01,759][INFO ][o.e.n.Node               ] version[5.3.2], pid[29980], build[3068195/2017-04-24T16:15:59.481Z], OS[Linux/4.4.0-77-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_131/25.131-b11]
[2017-05-12T15:12:02,630][INFO ][o.e.p.PluginsService     ] [aby1GZi] loaded module [aggs-matrix-stats]
[2017-05-12T15:12:02,631][INFO ][o.e.p.PluginsService     ] [aby1GZi] loaded module [ingest-common]
[2017-05-12T15:12:02,631][INFO ][o.e.p.PluginsService     ] [aby1GZi] loaded module [lang-expression]
[2017-05-12T15:12:02,631][INFO ][o.e.p.PluginsService     ] [aby1GZi] loaded module [lang-groovy]
[2017-05-12T15:12:02,631][INFO ][o.e.p.PluginsService     ] [aby1GZi] loaded module [lang-mustache]
[2017-05-12T15:12:02,631][INFO ][o.e.p.PluginsService     ] [aby1GZi] loaded module [lang-painless]
[2017-05-12T15:12:02,631][INFO ][o.e.p.PluginsService     ] [aby1GZi] loaded module [percolator]
[2017-05-12T15:12:02,632][INFO ][o.e.p.PluginsService     ] [aby1GZi] loaded module [reindex]
[2017-05-12T15:12:02,632][INFO ][o.e.p.PluginsService     ] [aby1GZi] loaded module [transport-netty3]
[2017-05-12T15:12:02,632][INFO ][o.e.p.PluginsService     ] [aby1GZi] loaded module [transport-netty4]
[2017-05-12T15:12:02,633][INFO ][o.e.p.PluginsService     ] [aby1GZi] loaded plugin [elasticsearch-analysis-ansj]
[2017-05-12T15:12:02,948][INFO ][o.a.e.p.AnalysisAnsjPlugin] regedit analyzer tokenizer named : base_ansj
[2017-05-12T15:12:02,949][INFO ][o.a.e.p.AnalysisAnsjPlugin] regedit analyzer tokenizer named : index_ansj
[2017-05-12T15:12:02,949][INFO ][o.a.e.p.AnalysisAnsjPlugin] regedit analyzer tokenizer named : query_ansj
[2017-05-12T15:12:02,949][INFO ][o.a.e.p.AnalysisAnsjPlugin] regedit analyzer tokenizer named : dic_ansj
[2017-05-12T15:12:02,949][INFO ][o.a.e.p.AnalysisAnsjPlugin] regedit analyzer tokenizer named : nlp_ansj
[2017-05-12T15:12:02,987][INFO ][o.a.e.p.AnalysisAnsjPlugin] regedit analyzer provider named : base_ansj
[2017-05-12T15:12:02,987][INFO ][o.a.e.p.AnalysisAnsjPlugin] regedit analyzer provider named : index_ansj
[2017-05-12T15:12:02,987][INFO ][o.a.e.p.AnalysisAnsjPlugin] regedit analyzer provider named : query_ansj
[2017-05-12T15:12:02,987][INFO ][o.a.e.p.AnalysisAnsjPlugin] regedit analyzer provider named : dic_ansj
[2017-05-12T15:12:02,988][INFO ][o.a.e.p.AnalysisAnsjPlugin] regedit analyzer provider named : nlp_ansj
[2017-05-12T15:12:04,414][INFO ][ansj-initializer         ] try to load ansj config file: /home/app/elasticsearch-5.3.2/config/analysis-ansj/ansj.cfg.yml
[2017-05-12T15:12:04,415][INFO ][ansj-initializer         ] try to load ansj config file: /home/app/elasticsearch-5.3.2/plugins/elasticsearch-analysis-ansj/config/ansj.cfg.yml
[2017-05-12T15:12:04,415][WARN ][ansj-initializer         ] can't find ansj config file
[2017-05-12T15:12:04,424][WARN ][o.a.u.MyStaticValue      ] not find ansj_library.properties. and err {} i think it is a bug!
[2017-05-12T15:12:04,425][WARN ][o.a.u.MyStaticValue      ] not find library.properties. and err {} i think it is a bug!
java.security.AccessControlException: access denied ("java.io.FilePermission" "/home/app/elasticsearch-5.3.2" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_131]
	at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_131]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_131]
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888) ~[?:1.8.0_131]
	at java.io.File.exists(File.java:814) ~[?:1.8.0_131]
	at org.nlpcn.commons.lang.util.FileFinder.find(FileFinder.java:52) ~[nlp-lang-1.7.2.jar:?]
	at org.ansj.util.MyStaticValue.<clinit>(MyStaticValue.java:79) [ansj_seg-5.1.1.jar:?]
	at org.ansj.elasticsearch.index.config.AnsjElasticConfigurator.flushConfig(AnsjElasticConfigurator.java:78) [elasticsearch-analysis-ansj-5.3.2.0.jar:?]
	at org.ansj.elasticsearch.index.config.AnsjElasticConfigurator.<init>(AnsjElasticConfigurator.java:70) [elasticsearch-analysis-ansj-5.3.2.0.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_131]
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:49) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:116) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:825) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:50) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:191) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:183) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:818) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:183) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:173) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:161) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:96) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:96) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:43) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.node.Node.<init>(Node.java:489) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.node.Node.<init>(Node.java:242) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.cli.Command.main(Command.java:88) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) [elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) [elasticsearch-5.3.2.jar:5.3.2]
[2017-05-12T15:12:04,439][WARN ][o.a.u.MyStaticValue      ] not find library.properties in classpath use it by default !
[2017-05-12T15:12:04,444][INFO ][o.a.d.i.File2Stream      ] path to stream /home/app/elasticsearch-5.3.2/config/ansj_library.properties
[2017-05-12T15:12:04,445][WARN ][ansj-initializer         ] /home/app/elasticsearch-5.3.2/config/ansj_library.properties load err
[2017-05-12T15:12:04,449][INFO ][o.a.d.i.File2Stream      ] path to stream library/ambiguity.dic
[2017-05-12T15:12:04,449][ERROR][o.a.l.AmbiguityLibrary   ] Init ambiguity library error :java.security.AccessControlException: access denied ("java.io.FilePermission" "library/ambiguity.dic" "read"), path: library/ambiguity.dic
[2017-05-12T15:12:04,451][INFO ][o.a.d.i.File2Stream      ] path to stream library/default.dic
[2017-05-12T15:12:04,451][ERROR][o.a.l.DicLibrary         ] Init ambiguity library error :java.security.AccessControlException: access denied ("java.io.FilePermission" "library/default.dic" "read"), path: library/default.dic
[2017-05-12T15:12:05,181][INFO ][o.a.l.DATDictionary      ] init core library ok use time : 711
[2017-05-12T15:12:05,738][INFO ][o.a.l.NgramLibrary       ] init ngram ok use time :454
[2017-05-12T15:12:05,741][INFO ][ansj-initializer         ] init ansj plugin ok , goodluck youyou
[2017-05-12T15:12:06,013][INFO ][o.e.n.Node               ] initialized
[2017-05-12T15:12:06,015][INFO ][o.e.n.Node               ] [aby1GZi] starting ...
[2017-05-12T15:12:06,202][INFO ][o.e.t.TransportService   ] [aby1GZi] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
^C[2017-05-12T15:12:07,346][INFO ][o.e.n.Node               ] [aby1GZi] stopping ...
[2017-05-12T15:12:07,362][INFO ][o.e.n.Node               ] [aby1GZi] stopped
[2017-05-12T15:12:07,362][INFO ][o.e.n.Node               ] [aby1GZi] closing ...
[2017-05-12T15:12:07,364][INFO ][o.e.h.n.Netty4HttpServerTransport] [aby1GZi] publish_address {127.0.0.1:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}
```

**Comment by shi-yuan** [comment]
Have a look at [Issue70](https://github.com/NLPchina/elasticsearch-analysis-ansj/issues/70)
